# This file was generated by GoReleaser. DO NOT EDIT.
cask "solitary" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "3361da81696ce6b0e9e60eaefbc0b6fbd78c3c94693134a1a55d91e46f4664f6"
      url "https://github.com/balakin/solitary/releases/download/v0.1.1/solitary_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b463507ec5317ba7acf2aa8a742a344f9fc48c735fcdf0ad5e04fca8a038e4ef"
      url "https://github.com/balakin/solitary/releases/download/v0.1.1/solitary_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "39f33c21d9a8d54c177d3bdfc79dbdc7a5d711b6f771fb02d637a351ac823d07"
      url "https://github.com/balakin/solitary/releases/download/v0.1.1/solitary_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb3d1176a38f49f35f0e795f400b3b8cc56555beffc6e1fe6cb1762406a3b8c6"
      url "https://github.com/balakin/solitary/releases/download/v0.1.1/solitary_linux_arm64.tar.gz"
    end
  end

  name "solitary"
  desc "Hypervisor-isolated cells for running coding agents off the leash"
  homepage "https://solitary.balakin.io"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "lima",
    ]

  binary "solitary"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/solitary"]
    end
  end

  # No zap stanza required

end
