# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solitary < Formula
  desc "Run coding agents on a VM, not on your machine"
  homepage "https://solitary.balakin.io"
  version "0.11.1"
  license "Apache-2.0"

  depends_on "lima"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balakin/solitary/releases/download/v0.11.1/solitary_darwin_amd64.tar.gz"
      sha256 "a7b63830346f54abbd464a4d92ec655b45a3210d3e6549b2b2b87ce14328a314"

      define_method(:install) do
        bin.install "solitary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balakin/solitary/releases/download/v0.11.1/solitary_darwin_arm64.tar.gz"
      sha256 "9067017445aa132923a2583bcd5908b16cd842cd29c184aa7ef3929ec9a55ee5"

      define_method(:install) do
        bin.install "solitary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balakin/solitary/releases/download/v0.11.1/solitary_linux_amd64.tar.gz"
      sha256 "fa1d0d57671ea4e171410c9b837473868ec216e2762b47eb41f694b5c25090b6"
      define_method(:install) do
        bin.install "solitary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balakin/solitary/releases/download/v0.11.1/solitary_linux_arm64.tar.gz"
      sha256 "3a42beada1abbb7380a56eccb09edab57c957de3ecef02405fa672c32002d8dc"
      define_method(:install) do
        bin.install "solitary"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/solitary --version")
  end
end
